//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ConsoleTs.HexVoucherService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VoucherServiceSoap", Namespace="http://tempuri.org/")]
    public partial class VoucherService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VoucherOOOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherCheckNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherCheckReturnOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherCheck_OOOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback Test2OperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherTransactionNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherTransactionReturnOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherSalesCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherCheck_BCPOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherCheck_BCPNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherQueryNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherTransactionRetreatRefundOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherTransactionWriteOffRefundOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherObsoleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback StoreInformationSynchronizeOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoucherCodeSynchronizeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VoucherService() {
            this.Url = global::ConsoleTs.Properties.Settings.Default.ConsoleTs_HexVoucherService_VoucherService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VoucherOOCompletedEventHandler VoucherOOCompleted;
        
        /// <remarks/>
        public event VoucherCheckCompletedEventHandler VoucherCheckCompleted;
        
        /// <remarks/>
        public event VoucherCheckNewCompletedEventHandler VoucherCheckNewCompleted;
        
        /// <remarks/>
        public event VoucherCheckReturnCompletedEventHandler VoucherCheckReturnCompleted;
        
        /// <remarks/>
        public event VoucherCheck_OOCompletedEventHandler VoucherCheck_OOCompleted;
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        public event Test2CompletedEventHandler Test2Completed;
        
        /// <remarks/>
        public event VoucherTransactionCompletedEventHandler VoucherTransactionCompleted;
        
        /// <remarks/>
        public event VoucherTransactionNewCompletedEventHandler VoucherTransactionNewCompleted;
        
        /// <remarks/>
        public event VoucherTransactionReturnCompletedEventHandler VoucherTransactionReturnCompleted;
        
        /// <remarks/>
        public event VoucherSalesCheckCompletedEventHandler VoucherSalesCheckCompleted;
        
        /// <remarks/>
        public event VoucherCheck_BCPCompletedEventHandler VoucherCheck_BCPCompleted;
        
        /// <remarks/>
        public event VoucherCheck_BCPNewCompletedEventHandler VoucherCheck_BCPNewCompleted;
        
        /// <remarks/>
        public event VoucherQueryCompletedEventHandler VoucherQueryCompleted;
        
        /// <remarks/>
        public event VoucherQueryNewCompletedEventHandler VoucherQueryNewCompleted;
        
        /// <remarks/>
        public event VoucherTransactionRetreatRefundCompletedEventHandler VoucherTransactionRetreatRefundCompleted;
        
        /// <remarks/>
        public event VoucherTransactionWriteOffRefundCompletedEventHandler VoucherTransactionWriteOffRefundCompleted;
        
        /// <remarks/>
        public event VoucherObsoleteCompletedEventHandler VoucherObsoleteCompleted;
        
        /// <remarks/>
        public event StoreInformationSynchronizeCompletedEventHandler StoreInformationSynchronizeCompleted;
        
        /// <remarks/>
        public event VoucherCodeSynchronizeCompletedEventHandler VoucherCodeSynchronizeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherOO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherOO(
                    string trans_tp, 
                    string voucher_no, 
                    string voucher_qty, 
                    string voucher_bcd, 
                    string bizdt_ord, 
                    string net_no_ord, 
                    string cust_name, 
                    string cust_tel, 
                    string cust_rmk, 
                    string rmk, 
                    string Sign, 
                    out string RtnTransTp, 
                    out string RtnMsg, 
                    out string RtnMsgNo, 
                    out string RtnVoucherBcd, 
                    out string RtnVoucherItem) {
            object[] results = this.Invoke("VoucherOO", new object[] {
                        trans_tp,
                        voucher_no,
                        voucher_qty,
                        voucher_bcd,
                        bizdt_ord,
                        net_no_ord,
                        cust_name,
                        cust_tel,
                        cust_rmk,
                        rmk,
                        Sign});
            RtnTransTp = ((string)(results[1]));
            RtnMsg = ((string)(results[2]));
            RtnMsgNo = ((string)(results[3]));
            RtnVoucherBcd = ((string)(results[4]));
            RtnVoucherItem = ((string)(results[5]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherOOAsync(string trans_tp, string voucher_no, string voucher_qty, string voucher_bcd, string bizdt_ord, string net_no_ord, string cust_name, string cust_tel, string cust_rmk, string rmk, string Sign) {
            this.VoucherOOAsync(trans_tp, voucher_no, voucher_qty, voucher_bcd, bizdt_ord, net_no_ord, cust_name, cust_tel, cust_rmk, rmk, Sign, null);
        }
        
        /// <remarks/>
        public void VoucherOOAsync(string trans_tp, string voucher_no, string voucher_qty, string voucher_bcd, string bizdt_ord, string net_no_ord, string cust_name, string cust_tel, string cust_rmk, string rmk, string Sign, object userState) {
            if ((this.VoucherOOOperationCompleted == null)) {
                this.VoucherOOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherOOOperationCompleted);
            }
            this.InvokeAsync("VoucherOO", new object[] {
                        trans_tp,
                        voucher_no,
                        voucher_qty,
                        voucher_bcd,
                        bizdt_ord,
                        net_no_ord,
                        cust_name,
                        cust_tel,
                        cust_rmk,
                        rmk,
                        Sign}, this.VoucherOOOperationCompleted, userState);
        }
        
        private void OnVoucherOOOperationCompleted(object arg) {
            if ((this.VoucherOOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherOOCompleted(this, new VoucherOOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherCheck(string VoucherNo, string StoreNo, string Sign, out string DisNo, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("VoucherCheck", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign});
            DisNo = ((string)(results[1]));
            RtnMsg = ((string)(results[2]));
            RtnMsgNo = ((string)(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherCheckAsync(string VoucherNo, string StoreNo, string Sign) {
            this.VoucherCheckAsync(VoucherNo, StoreNo, Sign, null);
        }
        
        /// <remarks/>
        public void VoucherCheckAsync(string VoucherNo, string StoreNo, string Sign, object userState) {
            if ((this.VoucherCheckOperationCompleted == null)) {
                this.VoucherCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherCheckOperationCompleted);
            }
            this.InvokeAsync("VoucherCheck", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign}, this.VoucherCheckOperationCompleted, userState);
        }
        
        private void OnVoucherCheckOperationCompleted(object arg) {
            if ((this.VoucherCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherCheckCompleted(this, new VoucherCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherCheckNew", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherCheckNew(string VoucherNo, string StoreNo, ref string Sign, out string VoucherItemNo, out string DisNo, out string NetAmt, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("VoucherCheckNew", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign});
            Sign = ((string)(results[1]));
            VoucherItemNo = ((string)(results[2]));
            DisNo = ((string)(results[3]));
            NetAmt = ((string)(results[4]));
            RtnMsg = ((string)(results[5]));
            RtnMsgNo = ((string)(results[6]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherCheckNewAsync(string VoucherNo, string StoreNo, string Sign) {
            this.VoucherCheckNewAsync(VoucherNo, StoreNo, Sign, null);
        }
        
        /// <remarks/>
        public void VoucherCheckNewAsync(string VoucherNo, string StoreNo, string Sign, object userState) {
            if ((this.VoucherCheckNewOperationCompleted == null)) {
                this.VoucherCheckNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherCheckNewOperationCompleted);
            }
            this.InvokeAsync("VoucherCheckNew", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign}, this.VoucherCheckNewOperationCompleted, userState);
        }
        
        private void OnVoucherCheckNewOperationCompleted(object arg) {
            if ((this.VoucherCheckNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherCheckNewCompleted(this, new VoucherCheckNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherCheckReturn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherCheckReturn(string VoucherNo, string StoreNo, string Sign, out string DisNo, out string NetAmt, out string ItemNo, out string TenderNo, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("VoucherCheckReturn", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign});
            DisNo = ((string)(results[1]));
            NetAmt = ((string)(results[2]));
            ItemNo = ((string)(results[3]));
            TenderNo = ((string)(results[4]));
            RtnMsg = ((string)(results[5]));
            RtnMsgNo = ((string)(results[6]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherCheckReturnAsync(string VoucherNo, string StoreNo, string Sign) {
            this.VoucherCheckReturnAsync(VoucherNo, StoreNo, Sign, null);
        }
        
        /// <remarks/>
        public void VoucherCheckReturnAsync(string VoucherNo, string StoreNo, string Sign, object userState) {
            if ((this.VoucherCheckReturnOperationCompleted == null)) {
                this.VoucherCheckReturnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherCheckReturnOperationCompleted);
            }
            this.InvokeAsync("VoucherCheckReturn", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign}, this.VoucherCheckReturnOperationCompleted, userState);
        }
        
        private void OnVoucherCheckReturnOperationCompleted(object arg) {
            if ((this.VoucherCheckReturnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherCheckReturnCompleted(this, new VoucherCheckReturnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherCheck_OO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherCheck_OO(string VoucherNo, string StoreNo, string Sign, out string DisNo, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("VoucherCheck_OO", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign});
            DisNo = ((string)(results[1]));
            RtnMsg = ((string)(results[2]));
            RtnMsgNo = ((string)(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherCheck_OOAsync(string VoucherNo, string StoreNo, string Sign) {
            this.VoucherCheck_OOAsync(VoucherNo, StoreNo, Sign, null);
        }
        
        /// <remarks/>
        public void VoucherCheck_OOAsync(string VoucherNo, string StoreNo, string Sign, object userState) {
            if ((this.VoucherCheck_OOOperationCompleted == null)) {
                this.VoucherCheck_OOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherCheck_OOOperationCompleted);
            }
            this.InvokeAsync("VoucherCheck_OO", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign}, this.VoucherCheck_OOOperationCompleted, userState);
        }
        
        private void OnVoucherCheck_OOOperationCompleted(object arg) {
            if ((this.VoucherCheck_OOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherCheck_OOCompleted(this, new VoucherCheck_OOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Test() {
            object[] results = this.Invoke("Test", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestAsync() {
            this.TestAsync(null);
        }
        
        /// <remarks/>
        public void TestAsync(object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[0], this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Test2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Test2() {
            object[] results = this.Invoke("Test2", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Test2Async() {
            this.Test2Async(null);
        }
        
        /// <remarks/>
        public void Test2Async(object userState) {
            if ((this.Test2OperationCompleted == null)) {
                this.Test2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnTest2OperationCompleted);
            }
            this.InvokeAsync("Test2", new object[0], this.Test2OperationCompleted, userState);
        }
        
        private void OnTest2OperationCompleted(object arg) {
            if ((this.Test2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Test2Completed(this, new Test2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherTransaction(int IsSale, string VoucherNo, string StoreNo, string TillNo, int SaleId, string UserCode, string SaleDate, string Sign, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("VoucherTransaction", new object[] {
                        IsSale,
                        VoucherNo,
                        StoreNo,
                        TillNo,
                        SaleId,
                        UserCode,
                        SaleDate,
                        Sign});
            RtnMsg = ((string)(results[1]));
            RtnMsgNo = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherTransactionAsync(int IsSale, string VoucherNo, string StoreNo, string TillNo, int SaleId, string UserCode, string SaleDate, string Sign) {
            this.VoucherTransactionAsync(IsSale, VoucherNo, StoreNo, TillNo, SaleId, UserCode, SaleDate, Sign, null);
        }
        
        /// <remarks/>
        public void VoucherTransactionAsync(int IsSale, string VoucherNo, string StoreNo, string TillNo, int SaleId, string UserCode, string SaleDate, string Sign, object userState) {
            if ((this.VoucherTransactionOperationCompleted == null)) {
                this.VoucherTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherTransactionOperationCompleted);
            }
            this.InvokeAsync("VoucherTransaction", new object[] {
                        IsSale,
                        VoucherNo,
                        StoreNo,
                        TillNo,
                        SaleId,
                        UserCode,
                        SaleDate,
                        Sign}, this.VoucherTransactionOperationCompleted, userState);
        }
        
        private void OnVoucherTransactionOperationCompleted(object arg) {
            if ((this.VoucherTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherTransactionCompleted(this, new VoucherTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherTransactionNew", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherTransactionNew(int IsSale, string VoucherNo, string StoreNo, string TillNo, int SaleId, string UserCode, string SaleDate, string NetAmt, string Distcount, string Tender, string TtransNo, string Sign, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("VoucherTransactionNew", new object[] {
                        IsSale,
                        VoucherNo,
                        StoreNo,
                        TillNo,
                        SaleId,
                        UserCode,
                        SaleDate,
                        NetAmt,
                        Distcount,
                        Tender,
                        TtransNo,
                        Sign});
            RtnMsg = ((string)(results[1]));
            RtnMsgNo = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherTransactionNewAsync(int IsSale, string VoucherNo, string StoreNo, string TillNo, int SaleId, string UserCode, string SaleDate, string NetAmt, string Distcount, string Tender, string TtransNo, string Sign) {
            this.VoucherTransactionNewAsync(IsSale, VoucherNo, StoreNo, TillNo, SaleId, UserCode, SaleDate, NetAmt, Distcount, Tender, TtransNo, Sign, null);
        }
        
        /// <remarks/>
        public void VoucherTransactionNewAsync(int IsSale, string VoucherNo, string StoreNo, string TillNo, int SaleId, string UserCode, string SaleDate, string NetAmt, string Distcount, string Tender, string TtransNo, string Sign, object userState) {
            if ((this.VoucherTransactionNewOperationCompleted == null)) {
                this.VoucherTransactionNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherTransactionNewOperationCompleted);
            }
            this.InvokeAsync("VoucherTransactionNew", new object[] {
                        IsSale,
                        VoucherNo,
                        StoreNo,
                        TillNo,
                        SaleId,
                        UserCode,
                        SaleDate,
                        NetAmt,
                        Distcount,
                        Tender,
                        TtransNo,
                        Sign}, this.VoucherTransactionNewOperationCompleted, userState);
        }
        
        private void OnVoucherTransactionNewOperationCompleted(object arg) {
            if ((this.VoucherTransactionNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherTransactionNewCompleted(this, new VoucherTransactionNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherTransactionReturn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherTransactionReturn(int IsRtn, string VoucherNo, string StoreNo, string TillNo, int SaleId, string StaffNo, string RtnDate, string TtransNo, string Sign, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("VoucherTransactionReturn", new object[] {
                        IsRtn,
                        VoucherNo,
                        StoreNo,
                        TillNo,
                        SaleId,
                        StaffNo,
                        RtnDate,
                        TtransNo,
                        Sign});
            RtnMsg = ((string)(results[1]));
            RtnMsgNo = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherTransactionReturnAsync(int IsRtn, string VoucherNo, string StoreNo, string TillNo, int SaleId, string StaffNo, string RtnDate, string TtransNo, string Sign) {
            this.VoucherTransactionReturnAsync(IsRtn, VoucherNo, StoreNo, TillNo, SaleId, StaffNo, RtnDate, TtransNo, Sign, null);
        }
        
        /// <remarks/>
        public void VoucherTransactionReturnAsync(int IsRtn, string VoucherNo, string StoreNo, string TillNo, int SaleId, string StaffNo, string RtnDate, string TtransNo, string Sign, object userState) {
            if ((this.VoucherTransactionReturnOperationCompleted == null)) {
                this.VoucherTransactionReturnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherTransactionReturnOperationCompleted);
            }
            this.InvokeAsync("VoucherTransactionReturn", new object[] {
                        IsRtn,
                        VoucherNo,
                        StoreNo,
                        TillNo,
                        SaleId,
                        StaffNo,
                        RtnDate,
                        TtransNo,
                        Sign}, this.VoucherTransactionReturnOperationCompleted, userState);
        }
        
        private void OnVoucherTransactionReturnOperationCompleted(object arg) {
            if ((this.VoucherTransactionReturnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherTransactionReturnCompleted(this, new VoucherTransactionReturnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherSalesCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherSalesCheck(string VoucherNo, string StoreNo, string Sign, out string ItemNo, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("VoucherSalesCheck", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign});
            ItemNo = ((string)(results[1]));
            RtnMsg = ((string)(results[2]));
            RtnMsgNo = ((string)(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherSalesCheckAsync(string VoucherNo, string StoreNo, string Sign) {
            this.VoucherSalesCheckAsync(VoucherNo, StoreNo, Sign, null);
        }
        
        /// <remarks/>
        public void VoucherSalesCheckAsync(string VoucherNo, string StoreNo, string Sign, object userState) {
            if ((this.VoucherSalesCheckOperationCompleted == null)) {
                this.VoucherSalesCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherSalesCheckOperationCompleted);
            }
            this.InvokeAsync("VoucherSalesCheck", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign}, this.VoucherSalesCheckOperationCompleted, userState);
        }
        
        private void OnVoucherSalesCheckOperationCompleted(object arg) {
            if ((this.VoucherSalesCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherSalesCheckCompleted(this, new VoucherSalesCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherCheck_BCP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherCheck_BCP(string VoucherNo, string StoreNo, string Sign, out string ItemNo, out string DisNo, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("VoucherCheck_BCP", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign});
            ItemNo = ((string)(results[1]));
            DisNo = ((string)(results[2]));
            RtnMsg = ((string)(results[3]));
            RtnMsgNo = ((string)(results[4]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherCheck_BCPAsync(string VoucherNo, string StoreNo, string Sign) {
            this.VoucherCheck_BCPAsync(VoucherNo, StoreNo, Sign, null);
        }
        
        /// <remarks/>
        public void VoucherCheck_BCPAsync(string VoucherNo, string StoreNo, string Sign, object userState) {
            if ((this.VoucherCheck_BCPOperationCompleted == null)) {
                this.VoucherCheck_BCPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherCheck_BCPOperationCompleted);
            }
            this.InvokeAsync("VoucherCheck_BCP", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign}, this.VoucherCheck_BCPOperationCompleted, userState);
        }
        
        private void OnVoucherCheck_BCPOperationCompleted(object arg) {
            if ((this.VoucherCheck_BCPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherCheck_BCPCompleted(this, new VoucherCheck_BCPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherCheck_BCPNew", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherCheck_BCPNew(string VoucherNo, string StoreNo, string Sign, out string VoucherItemNo, out string ItemNo, out string DisNo, out string NetAmt, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("VoucherCheck_BCPNew", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign});
            VoucherItemNo = ((string)(results[1]));
            ItemNo = ((string)(results[2]));
            DisNo = ((string)(results[3]));
            NetAmt = ((string)(results[4]));
            RtnMsg = ((string)(results[5]));
            RtnMsgNo = ((string)(results[6]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherCheck_BCPNewAsync(string VoucherNo, string StoreNo, string Sign) {
            this.VoucherCheck_BCPNewAsync(VoucherNo, StoreNo, Sign, null);
        }
        
        /// <remarks/>
        public void VoucherCheck_BCPNewAsync(string VoucherNo, string StoreNo, string Sign, object userState) {
            if ((this.VoucherCheck_BCPNewOperationCompleted == null)) {
                this.VoucherCheck_BCPNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherCheck_BCPNewOperationCompleted);
            }
            this.InvokeAsync("VoucherCheck_BCPNew", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign}, this.VoucherCheck_BCPNewOperationCompleted, userState);
        }
        
        private void OnVoucherCheck_BCPNewOperationCompleted(object arg) {
            if ((this.VoucherCheck_BCPNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherCheck_BCPNewCompleted(this, new VoucherCheck_BCPNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherQuery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherQuery(string VoucherNo, string StoreNo, ref string Sign, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("VoucherQuery", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign});
            Sign = ((string)(results[1]));
            RtnMsg = ((string)(results[2]));
            RtnMsgNo = ((string)(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherQueryAsync(string VoucherNo, string StoreNo, string Sign) {
            this.VoucherQueryAsync(VoucherNo, StoreNo, Sign, null);
        }
        
        /// <remarks/>
        public void VoucherQueryAsync(string VoucherNo, string StoreNo, string Sign, object userState) {
            if ((this.VoucherQueryOperationCompleted == null)) {
                this.VoucherQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherQueryOperationCompleted);
            }
            this.InvokeAsync("VoucherQuery", new object[] {
                        VoucherNo,
                        StoreNo,
                        Sign}, this.VoucherQueryOperationCompleted, userState);
        }
        
        private void OnVoucherQueryOperationCompleted(object arg) {
            if ((this.VoucherQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherQueryCompleted(this, new VoucherQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherQueryNew", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherQueryNew(string VoucherNo, string Sign, out string VoucherType, out string VoucherItemNo, out string VoucherNos, out string VoucherStatus, out string StoreNo, out string ActivedTime, out string CertificatedTime, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("VoucherQueryNew", new object[] {
                        VoucherNo,
                        Sign});
            VoucherType = ((string)(results[1]));
            VoucherItemNo = ((string)(results[2]));
            VoucherNos = ((string)(results[3]));
            VoucherStatus = ((string)(results[4]));
            StoreNo = ((string)(results[5]));
            ActivedTime = ((string)(results[6]));
            CertificatedTime = ((string)(results[7]));
            RtnMsg = ((string)(results[8]));
            RtnMsgNo = ((string)(results[9]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherQueryNewAsync(string VoucherNo, string Sign) {
            this.VoucherQueryNewAsync(VoucherNo, Sign, null);
        }
        
        /// <remarks/>
        public void VoucherQueryNewAsync(string VoucherNo, string Sign, object userState) {
            if ((this.VoucherQueryNewOperationCompleted == null)) {
                this.VoucherQueryNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherQueryNewOperationCompleted);
            }
            this.InvokeAsync("VoucherQueryNew", new object[] {
                        VoucherNo,
                        Sign}, this.VoucherQueryNewOperationCompleted, userState);
        }
        
        private void OnVoucherQueryNewOperationCompleted(object arg) {
            if ((this.VoucherQueryNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherQueryNewCompleted(this, new VoucherQueryNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherTransactionRetreatRefund", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherTransactionRetreatRefund(string TransNo, string VoucherNo, string Sign, string StoreNo, string TillNo, int SaleId, string SaleDate, string Remarks1, string Remarks2, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("VoucherTransactionRetreatRefund", new object[] {
                        TransNo,
                        VoucherNo,
                        Sign,
                        StoreNo,
                        TillNo,
                        SaleId,
                        SaleDate,
                        Remarks1,
                        Remarks2});
            RtnMsg = ((string)(results[1]));
            RtnMsgNo = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherTransactionRetreatRefundAsync(string TransNo, string VoucherNo, string Sign, string StoreNo, string TillNo, int SaleId, string SaleDate, string Remarks1, string Remarks2) {
            this.VoucherTransactionRetreatRefundAsync(TransNo, VoucherNo, Sign, StoreNo, TillNo, SaleId, SaleDate, Remarks1, Remarks2, null);
        }
        
        /// <remarks/>
        public void VoucherTransactionRetreatRefundAsync(string TransNo, string VoucherNo, string Sign, string StoreNo, string TillNo, int SaleId, string SaleDate, string Remarks1, string Remarks2, object userState) {
            if ((this.VoucherTransactionRetreatRefundOperationCompleted == null)) {
                this.VoucherTransactionRetreatRefundOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherTransactionRetreatRefundOperationCompleted);
            }
            this.InvokeAsync("VoucherTransactionRetreatRefund", new object[] {
                        TransNo,
                        VoucherNo,
                        Sign,
                        StoreNo,
                        TillNo,
                        SaleId,
                        SaleDate,
                        Remarks1,
                        Remarks2}, this.VoucherTransactionRetreatRefundOperationCompleted, userState);
        }
        
        private void OnVoucherTransactionRetreatRefundOperationCompleted(object arg) {
            if ((this.VoucherTransactionRetreatRefundCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherTransactionRetreatRefundCompleted(this, new VoucherTransactionRetreatRefundCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherTransactionWriteOffRefund", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherTransactionWriteOffRefund(string TransNo, string VoucherNo, string Sign, string StoreNo, string TillNo, int SaleId, string SaleDate, string Remarks1, string Remarks2, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("VoucherTransactionWriteOffRefund", new object[] {
                        TransNo,
                        VoucherNo,
                        Sign,
                        StoreNo,
                        TillNo,
                        SaleId,
                        SaleDate,
                        Remarks1,
                        Remarks2});
            RtnMsg = ((string)(results[1]));
            RtnMsgNo = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherTransactionWriteOffRefundAsync(string TransNo, string VoucherNo, string Sign, string StoreNo, string TillNo, int SaleId, string SaleDate, string Remarks1, string Remarks2) {
            this.VoucherTransactionWriteOffRefundAsync(TransNo, VoucherNo, Sign, StoreNo, TillNo, SaleId, SaleDate, Remarks1, Remarks2, null);
        }
        
        /// <remarks/>
        public void VoucherTransactionWriteOffRefundAsync(string TransNo, string VoucherNo, string Sign, string StoreNo, string TillNo, int SaleId, string SaleDate, string Remarks1, string Remarks2, object userState) {
            if ((this.VoucherTransactionWriteOffRefundOperationCompleted == null)) {
                this.VoucherTransactionWriteOffRefundOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherTransactionWriteOffRefundOperationCompleted);
            }
            this.InvokeAsync("VoucherTransactionWriteOffRefund", new object[] {
                        TransNo,
                        VoucherNo,
                        Sign,
                        StoreNo,
                        TillNo,
                        SaleId,
                        SaleDate,
                        Remarks1,
                        Remarks2}, this.VoucherTransactionWriteOffRefundOperationCompleted, userState);
        }
        
        private void OnVoucherTransactionWriteOffRefundOperationCompleted(object arg) {
            if ((this.VoucherTransactionWriteOffRefundCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherTransactionWriteOffRefundCompleted(this, new VoucherTransactionWriteOffRefundCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherObsolete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherObsolete(string VoucherNo, string UpdateDate, string Sign, string Remarks1, string Remarks2, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("VoucherObsolete", new object[] {
                        VoucherNo,
                        UpdateDate,
                        Sign,
                        Remarks1,
                        Remarks2});
            RtnMsg = ((string)(results[1]));
            RtnMsgNo = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherObsoleteAsync(string VoucherNo, string UpdateDate, string Sign, string Remarks1, string Remarks2) {
            this.VoucherObsoleteAsync(VoucherNo, UpdateDate, Sign, Remarks1, Remarks2, null);
        }
        
        /// <remarks/>
        public void VoucherObsoleteAsync(string VoucherNo, string UpdateDate, string Sign, string Remarks1, string Remarks2, object userState) {
            if ((this.VoucherObsoleteOperationCompleted == null)) {
                this.VoucherObsoleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherObsoleteOperationCompleted);
            }
            this.InvokeAsync("VoucherObsolete", new object[] {
                        VoucherNo,
                        UpdateDate,
                        Sign,
                        Remarks1,
                        Remarks2}, this.VoucherObsoleteOperationCompleted, userState);
        }
        
        private void OnVoucherObsoleteOperationCompleted(object arg) {
            if ((this.VoucherObsoleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherObsoleteCompleted(this, new VoucherObsoleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StoreInformationSynchronize", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StoreInformationSynchronize(string Province, string City, string Sign, string Company, string StoreNo, string StoreName, string StoreAddr, string StoreEmail, string StoreTel, string StorePosNum, string OperateType, string Remarks1, string Remarks2, out string RtnMsg, out string RtnMsgNo) {
            object[] results = this.Invoke("StoreInformationSynchronize", new object[] {
                        Province,
                        City,
                        Sign,
                        Company,
                        StoreNo,
                        StoreName,
                        StoreAddr,
                        StoreEmail,
                        StoreTel,
                        StorePosNum,
                        OperateType,
                        Remarks1,
                        Remarks2});
            RtnMsg = ((string)(results[1]));
            RtnMsgNo = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StoreInformationSynchronizeAsync(string Province, string City, string Sign, string Company, string StoreNo, string StoreName, string StoreAddr, string StoreEmail, string StoreTel, string StorePosNum, string OperateType, string Remarks1, string Remarks2) {
            this.StoreInformationSynchronizeAsync(Province, City, Sign, Company, StoreNo, StoreName, StoreAddr, StoreEmail, StoreTel, StorePosNum, OperateType, Remarks1, Remarks2, null);
        }
        
        /// <remarks/>
        public void StoreInformationSynchronizeAsync(string Province, string City, string Sign, string Company, string StoreNo, string StoreName, string StoreAddr, string StoreEmail, string StoreTel, string StorePosNum, string OperateType, string Remarks1, string Remarks2, object userState) {
            if ((this.StoreInformationSynchronizeOperationCompleted == null)) {
                this.StoreInformationSynchronizeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStoreInformationSynchronizeOperationCompleted);
            }
            this.InvokeAsync("StoreInformationSynchronize", new object[] {
                        Province,
                        City,
                        Sign,
                        Company,
                        StoreNo,
                        StoreName,
                        StoreAddr,
                        StoreEmail,
                        StoreTel,
                        StorePosNum,
                        OperateType,
                        Remarks1,
                        Remarks2}, this.StoreInformationSynchronizeOperationCompleted, userState);
        }
        
        private void OnStoreInformationSynchronizeOperationCompleted(object arg) {
            if ((this.StoreInformationSynchronizeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StoreInformationSynchronizeCompleted(this, new StoreInformationSynchronizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoucherCodeSynchronize", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoucherCodeSynchronize(string VoucherName, string VoucherNo, string Sign, string BarcodeUnit, string StartDate, string ExpiredDate, string UpdateDate, string Remarks1, string Remarks2, out string RtnMsg, out string RtnMsgNo, out string RtnVoucherName, out string RtnVoucherNo, out string RtnVoucherBCD) {
            object[] results = this.Invoke("VoucherCodeSynchronize", new object[] {
                        VoucherName,
                        VoucherNo,
                        Sign,
                        BarcodeUnit,
                        StartDate,
                        ExpiredDate,
                        UpdateDate,
                        Remarks1,
                        Remarks2});
            RtnMsg = ((string)(results[1]));
            RtnMsgNo = ((string)(results[2]));
            RtnVoucherName = ((string)(results[3]));
            RtnVoucherNo = ((string)(results[4]));
            RtnVoucherBCD = ((string)(results[5]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoucherCodeSynchronizeAsync(string VoucherName, string VoucherNo, string Sign, string BarcodeUnit, string StartDate, string ExpiredDate, string UpdateDate, string Remarks1, string Remarks2) {
            this.VoucherCodeSynchronizeAsync(VoucherName, VoucherNo, Sign, BarcodeUnit, StartDate, ExpiredDate, UpdateDate, Remarks1, Remarks2, null);
        }
        
        /// <remarks/>
        public void VoucherCodeSynchronizeAsync(string VoucherName, string VoucherNo, string Sign, string BarcodeUnit, string StartDate, string ExpiredDate, string UpdateDate, string Remarks1, string Remarks2, object userState) {
            if ((this.VoucherCodeSynchronizeOperationCompleted == null)) {
                this.VoucherCodeSynchronizeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoucherCodeSynchronizeOperationCompleted);
            }
            this.InvokeAsync("VoucherCodeSynchronize", new object[] {
                        VoucherName,
                        VoucherNo,
                        Sign,
                        BarcodeUnit,
                        StartDate,
                        ExpiredDate,
                        UpdateDate,
                        Remarks1,
                        Remarks2}, this.VoucherCodeSynchronizeOperationCompleted, userState);
        }
        
        private void OnVoucherCodeSynchronizeOperationCompleted(object arg) {
            if ((this.VoucherCodeSynchronizeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoucherCodeSynchronizeCompleted(this, new VoucherCodeSynchronizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherOOCompletedEventHandler(object sender, VoucherOOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherOOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherOOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string RtnTransTp {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string RtnVoucherBcd {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string RtnVoucherItem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherCheckCompletedEventHandler(object sender, VoucherCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string DisNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherCheckNewCompletedEventHandler(object sender, VoucherCheckNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherCheckNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherCheckNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Sign {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string VoucherItemNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string DisNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string NetAmt {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherCheckReturnCompletedEventHandler(object sender, VoucherCheckReturnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherCheckReturnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherCheckReturnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string DisNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string NetAmt {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string ItemNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string TenderNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherCheck_OOCompletedEventHandler(object sender, VoucherCheck_OOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherCheck_OOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherCheck_OOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string DisNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void TestCompletedEventHandler(object sender, TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void Test2CompletedEventHandler(object sender, Test2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Test2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Test2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherTransactionCompletedEventHandler(object sender, VoucherTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherTransactionNewCompletedEventHandler(object sender, VoucherTransactionNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherTransactionNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherTransactionNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherTransactionReturnCompletedEventHandler(object sender, VoucherTransactionReturnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherTransactionReturnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherTransactionReturnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherSalesCheckCompletedEventHandler(object sender, VoucherSalesCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherSalesCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherSalesCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ItemNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherCheck_BCPCompletedEventHandler(object sender, VoucherCheck_BCPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherCheck_BCPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherCheck_BCPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ItemNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string DisNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherCheck_BCPNewCompletedEventHandler(object sender, VoucherCheck_BCPNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherCheck_BCPNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherCheck_BCPNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string VoucherItemNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ItemNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string DisNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string NetAmt {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherQueryCompletedEventHandler(object sender, VoucherQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Sign {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherQueryNewCompletedEventHandler(object sender, VoucherQueryNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherQueryNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherQueryNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string VoucherType {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string VoucherItemNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string VoucherNos {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string VoucherStatus {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string StoreNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string ActivedTime {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
        
        /// <remarks/>
        public string CertificatedTime {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[7]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[8]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[9]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherTransactionRetreatRefundCompletedEventHandler(object sender, VoucherTransactionRetreatRefundCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherTransactionRetreatRefundCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherTransactionRetreatRefundCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherTransactionWriteOffRefundCompletedEventHandler(object sender, VoucherTransactionWriteOffRefundCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherTransactionWriteOffRefundCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherTransactionWriteOffRefundCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherObsoleteCompletedEventHandler(object sender, VoucherObsoleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherObsoleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherObsoleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void StoreInformationSynchronizeCompletedEventHandler(object sender, StoreInformationSynchronizeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StoreInformationSynchronizeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StoreInformationSynchronizeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void VoucherCodeSynchronizeCompletedEventHandler(object sender, VoucherCodeSynchronizeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoucherCodeSynchronizeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoucherCodeSynchronizeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string RtnMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string RtnMsgNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string RtnVoucherName {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string RtnVoucherNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string RtnVoucherBCD {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
}

#pragma warning restore 1591